### ISSUE TITLE
Is it possible to show only some of the fields in the preview?

### ISSUE THREAD

**Issue by lucasdidthis** [jongacnik/kirby-fields-block#10]
Hej hej,

loving your Plugin, but it would be awesome to hide some fields from the preview. I'd love to have the main content be editable in the preview, but would keep additional settings hidden there (only available via the editing option).

Is this possible?
Or any plans or making that possible?

Thanks again,
Cheers Lucas

**Comment by jongacnik** [comment]
Hi Lucas,

No plans for that since the plugin is actually very simple at the moment, and just passes the entire blueprint to the form component (https://github.com/jongacnik/kirby-fields-block/blob/main/src/FieldsBlock.vue#L10). More complex behavior like that might be better suited in a fork of this plugin, or a request to be included as a future core feature.

Thanks!
J
